// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCewZSwvd0nZqjgfpnk-NE8-nBoYgMCHSs',
    appId: '1:578570832:web:f24859a1ed7dbeb2f95f55',
    messagingSenderId: '578570832',
    projectId: 'desafio-flutter-ab329',
    authDomain: 'desafio-flutter-ab329.firebaseapp.com',
    storageBucket: 'desafio-flutter-ab329.firebasestorage.app',
    measurementId: 'G-GEXTTZCJV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1t6pa5lv9IIA3rQVHDT3JgLRtRTnuUc0',
    appId: '1:578570832:android:b97f8e4c39c59406f95f55',
    messagingSenderId: '578570832',
    projectId: 'desafio-flutter-ab329',
    storageBucket: 'desafio-flutter-ab329.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVbUPwZ3HLZZ_CFdgQl0Cd4Qa91onHYa4',
    appId: '1:578570832:ios:274b1683fe6dc4c2f95f55',
    messagingSenderId: '578570832',
    projectId: 'desafio-flutter-ab329',
    storageBucket: 'desafio-flutter-ab329.firebasestorage.app',
    iosBundleId: 'com.example.desafioFlutter',
  );
}
